### ISSUE TITLE
Help. Errors when adding a new source.

### ISSUE THREAD

**Issue by SainathKaluva** [matthieu-foucault/diggit-developers_activity#1]
Hi.

I downloaded this using the VM provided with the research paper. I tried adding new sources. And I receive the following errors. I could not exactly figure it out what they mean. I think it would be easy for you to understand.

    fse@fse-VirtualBox ~/Desktop/turnover_workdir $ dgit sources list
    [cloned]  1: https://github.com/angular/angular.js.git
    [cloned]  2: https://github.com/matthieu-foucault/jquery.git
    [cloned]  3: https://github.com/rails/rails.git
    [cloned]  4: https://github.com/jenkinsci/jenkins.git
    [cloned]  5: https://github.com/ansible/ansible.git
    [cloned]  6: https://github.com/golang/blog
    [cloned]  7: https://github.com/ejwa/gitinspector
     [error]  listed 7 sources including 2 errors
    
```
fse@fse-VirtualBox ~/Desktop/turnover_workdir $ dgit sources errors
    [cloned]  https://github.com/golang/blog
    [folder]  /home/fse/Desktop/turnover_workdir/sources/https_github_com_golang_blog
     [error]  NoMethodError
   [message]  undefined method `[]' for nil:NilClass
 [backtrace]  
/home/fse/.diggit/includes/developers_activity/activity_analysis.rb:25:in `load_options'
/home/fse/.diggit/includes/developers_activity/activity_analysis.rb:17:in `initialize'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `new'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `block in load_analyses'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `map'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `load_analyses'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:224:in `block in analyses'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:218:in `each'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:218:in `analyses'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/fse/Desktop/diggit_master/bin/dgit:6:in `<main>'
    [cloned]  https://github.com/ejwa/gitinspector
    [folder]  /home/fse/Desktop/turnover_workdir/sources/https_github_com_ejwa_gitinspector
     [error]  NoMethodError
   [message]  undefined method `[]' for nil:NilClass
 [backtrace]  
/home/fse/.diggit/includes/developers_activity/activity_analysis.rb:25:in `load_options'
/home/fse/.diggit/includes/developers_activity/activity_analysis.rb:17:in `initialize'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `new'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `block in load_analyses'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `map'
/home/fse/Desktop/diggit_master/lib/diggit_core.rb:155:in `load_analyses'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:224:in `block in analyses'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:218:in `each'
/home/fse/Desktop/diggit_master/lib/diggit_cli.rb:218:in `analyses'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/home/fse/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/home/fse/Desktop/diggit_master/bin/dgit:6:in `<main>'
```    
Thanks in advance.

**Comment by matthieu-foucault** [comment]
It looks like you did not add the configuration for the sources you added. If I recall (it's been more than two years so my memory is hazy), there should be a configuration file that contains options for the different sources, e.g. the list of modules, releases, etc. Look at the existing configuration for the other sources and try to replicate that for the two you added.
